-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgN+HDPeYwOmmqHMLM
EwUw+lYGzIuUeR9wvAjNqFL4BfCgCgYIKoZIzj0DAQehRANCAAR+86EiU987tMLc
92wovu/5ERw7mwZC4curPOtZgZHQgX80wORPybvuBOLvBUGqh8YzEhCl9B0bhKZv
udWN4hdu
-----END PRIVATE KEY-----